authors=[Daniel Corbani](https\://danielcorbani.art.br/)
categories=Video & Vision,Utilities,GUI
maxRevision=0
minRevision=0
name=Luna Video Mapping
paragraph=
prettyVersion=1.0.0-beta
sentence=A video mapping library with a user interface.
url=https\://luna.art.br/
version=0
