site_name: Luna Video Mapping Library
site_url: "https://danielcorbani.github.io/Luna-Video-Mapping/"

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.top
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: GPL 2.0 License.

plugins:
  - search
  - offline

nav:
  - Home: index.md
  - Installation: getting-started.md
  - Examples: examples.md
  - API Reference: reference.md
  - Download: download.md
#  - Development: develop.md
